site_name: Selfcash
repo_name: '2020-1-Selfcash'
repo_url: 'https://github.com/2020-1-Selfcash/Docs'

nav:
    - Home: index.md
    - Políticas: 
        - Branch: policies/branches.md
        - Commit: policies/commits.md
        - Pull Request: policies/pull-request.md

theme: readthedocs
